language: android
dist: trusty
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
#    - build-tools-26.0.2
#    - android-26
#    - extra-android-support
#    - extra-android-m2repository
#    - extra-google-m2repository
#    - addon-google_apis-google-26
#    - sys-img-x86-android-26

  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - pip install --user codecov    #Install codecov

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - ABI=armeabi-v7a
    - EMU_FLAVOR=default # use google_apis flavor if no default flavor emulator
    # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  matrix:
    #- ANDROID_TARGET=android-17 ANDROID_ABI=google_apis/armeabi-v7a
    #- ANDROID_TARGET=android-29 ANDROID_ABI=armeabi-v7a
#    - API=21
    - API=24
# Emulator Management: Create, Start and Wait
install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid harmless sdkmanager warning
  - echo y | sdkmanager "platform-tools" #>/dev/null
  - echo y | sdkmanager "tools" #>/dev/null # A second time per Travis docs, gets latest versions
  - echo y | sdkmanager "build-tools;29.0.2" >/dev/null # Implicit gradle dependency - gradle drives changes
  - echo y | sdkmanager "platforms;android-$API" >/dev/null # We need the API of the emulator we will run
  - echo y | sdkmanager "platforms;android-29" >/dev/null # We need the API of the current compileSdkVersion from gradle.properties
  - echo y | sdkmanager --channel=4 "emulator" # Experiment with canary, specifying 28.0.3 (prior version) did not work
  - ls -lat ${ANDROID_HOME}/emulator
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | sdkmanager "system-images;android-$API;$EMU_FLAVOR;$ABI" #>/dev/null # install our emulator
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI" -c 10M
  - emulator -verbose -avd test -no-accel -no-snapshot -no-window $AUDIO -camera-back none -camera-front none -selinux permissive -qemu -m 1536 &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

#script: ./gradlew connectedAndroidTest

after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - codecov                       #Run codecov

#script:
#  - ./gradlew clean build test jacocoTestReport check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/